/*
Crossid API

# Introduction  Crossid API allows you to manage resources in a simple, programmatic way using conventional HTTP requests.  All of the functionality that you are familiar with in the Crossid UI is also available through this API, allowing you to code actions that suites your requirements.  The rest of this page provides a general overview about the API design and technology that has been implemented.  ## Requests  ## HTTP Statuses  ## Meta  ### Sample Links Object  ## Rate Limit  ## Curl Examples  ## OpenAPI Specification  Crossid API conforms the OpenAPI V3 specification.  The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which  allows both humans and computers to discover and understand the capabilities of the service without access to source  code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what  interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service. 

API version: 2.0.0
Contact: api-engineering@crossid.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// ResourceTypeSchemaExt ResourceType schema extension.
type ResourceTypeSchemaExt struct {
	// The id of the schema (e.g., \"risk\")
	Schema *string `json:"schema,omitempty"`
	// True if every resource must have this schema extension.
	Required *bool `json:"required,omitempty"`
}

// NewResourceTypeSchemaExt instantiates a new ResourceTypeSchemaExt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceTypeSchemaExt() *ResourceTypeSchemaExt {
	this := ResourceTypeSchemaExt{}
	return &this
}

// NewResourceTypeSchemaExtWithDefaults instantiates a new ResourceTypeSchemaExt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceTypeSchemaExtWithDefaults() *ResourceTypeSchemaExt {
	this := ResourceTypeSchemaExt{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *ResourceTypeSchemaExt) GetSchema() string {
	if o == nil || o.Schema == nil {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTypeSchemaExt) GetSchemaOk() (*string, bool) {
	if o == nil || o.Schema == nil {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ResourceTypeSchemaExt) HasSchema() bool {
	if o != nil && o.Schema != nil {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *ResourceTypeSchemaExt) SetSchema(v string) {
	o.Schema = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *ResourceTypeSchemaExt) GetRequired() bool {
	if o == nil || o.Required == nil {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceTypeSchemaExt) GetRequiredOk() (*bool, bool) {
	if o == nil || o.Required == nil {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *ResourceTypeSchemaExt) HasRequired() bool {
	if o != nil && o.Required != nil {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *ResourceTypeSchemaExt) SetRequired(v bool) {
	o.Required = &v
}

func (o ResourceTypeSchemaExt) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if o.Required != nil {
		toSerialize["required"] = o.Required
	}
	return json.Marshal(toSerialize)
}

type NullableResourceTypeSchemaExt struct {
	value *ResourceTypeSchemaExt
	isSet bool
}

func (v NullableResourceTypeSchemaExt) Get() *ResourceTypeSchemaExt {
	return v.value
}

func (v *NullableResourceTypeSchemaExt) Set(val *ResourceTypeSchemaExt) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceTypeSchemaExt) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceTypeSchemaExt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceTypeSchemaExt(val *ResourceTypeSchemaExt) *NullableResourceTypeSchemaExt {
	return &NullableResourceTypeSchemaExt{value: val, isSet: true}
}

func (v NullableResourceTypeSchemaExt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceTypeSchemaExt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


