/*
Crossid API

# Introduction  Crossid API allows you to manage resources in a simple, programmatic way using conventional HTTP requests.  All of the functionality that you are familiar with in the Crossid UI is also available through this API, allowing you to code actions that suites your requirements.  The rest of this page provides a general overview about the API design and technology that has been implemented.  ## Requests  ## HTTP Statuses  ## Meta  ### Sample Links Object  ## Rate Limit  ## Curl Examples  ## OpenAPI Specification  Crossid API conforms the OpenAPI V3 specification.  The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which  allows both humans and computers to discover and understand the capabilities of the service without access to source  code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what  interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service. 

API version: 2.0.0
Contact: api-engineering@crossid.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cidclient

import (
	"encoding/json"
)

// AttributeSearch struct for AttributeSearch
type AttributeSearch struct {
	Boost *int32 `json:"boost,omitempty"`
	Fuzziness *int32 `json:"fuzziness,omitempty"`
}

// NewAttributeSearch instantiates a new AttributeSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributeSearch() *AttributeSearch {
	this := AttributeSearch{}
	return &this
}

// NewAttributeSearchWithDefaults instantiates a new AttributeSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributeSearchWithDefaults() *AttributeSearch {
	this := AttributeSearch{}
	return &this
}

// GetBoost returns the Boost field value if set, zero value otherwise.
func (o *AttributeSearch) GetBoost() int32 {
	if o == nil || o.Boost == nil {
		var ret int32
		return ret
	}
	return *o.Boost
}

// GetBoostOk returns a tuple with the Boost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributeSearch) GetBoostOk() (*int32, bool) {
	if o == nil || o.Boost == nil {
		return nil, false
	}
	return o.Boost, true
}

// HasBoost returns a boolean if a field has been set.
func (o *AttributeSearch) HasBoost() bool {
	if o != nil && o.Boost != nil {
		return true
	}

	return false
}

// SetBoost gets a reference to the given int32 and assigns it to the Boost field.
func (o *AttributeSearch) SetBoost(v int32) {
	o.Boost = &v
}

// GetFuzziness returns the Fuzziness field value if set, zero value otherwise.
func (o *AttributeSearch) GetFuzziness() int32 {
	if o == nil || o.Fuzziness == nil {
		var ret int32
		return ret
	}
	return *o.Fuzziness
}

// GetFuzzinessOk returns a tuple with the Fuzziness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributeSearch) GetFuzzinessOk() (*int32, bool) {
	if o == nil || o.Fuzziness == nil {
		return nil, false
	}
	return o.Fuzziness, true
}

// HasFuzziness returns a boolean if a field has been set.
func (o *AttributeSearch) HasFuzziness() bool {
	if o != nil && o.Fuzziness != nil {
		return true
	}

	return false
}

// SetFuzziness gets a reference to the given int32 and assigns it to the Fuzziness field.
func (o *AttributeSearch) SetFuzziness(v int32) {
	o.Fuzziness = &v
}

func (o AttributeSearch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Boost != nil {
		toSerialize["boost"] = o.Boost
	}
	if o.Fuzziness != nil {
		toSerialize["fuzziness"] = o.Fuzziness
	}
	return json.Marshal(toSerialize)
}

type NullableAttributeSearch struct {
	value *AttributeSearch
	isSet bool
}

func (v NullableAttributeSearch) Get() *AttributeSearch {
	return v.value
}

func (v *NullableAttributeSearch) Set(val *AttributeSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeSearch(val *AttributeSearch) *NullableAttributeSearch {
	return &NullableAttributeSearch{value: val, isSet: true}
}

func (v NullableAttributeSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


